export const ENV = {
    appwriteEndpoint: import.meta.env.VITE_APPWRITE_ENDPOINT,
    appwriteProjectId: import.meta.env.VITE_APPWRITE_PROJECT_ID,
    databaseId: import.meta.env.VITE_APPWRITE_DATABASE_ID,
    adminFunctionUsers: import.meta.env.VITE_APPWRITE_USERS_FUNCTION,
    storageBucketId: import.meta.env.VITE_APPWRITE_STORAGE_BUCKET_ID,
    googleClientId: import.meta.env.VITE_GOOGLE_CLIENT_ID,
    googleAuthUrl: import.meta.env.VITE_GOOGLE_AUTH_URL,
    passwordResetUrl: import.meta.env.VITE_PASSWORD_RESET_URL,
    infraStatusUrl: import.meta.env.VITE_INFRA_STATUS_URL,
    appwriteConsoleUrl: import.meta.env.VITE_APPWRITE_CONSOLE_URL,
    renderConsoleUrl: import.meta.env.VITE_RENDER_CONSOLE_URL,
    cloudflareConsoleUrl: import.meta.env.VITE_CLOUDFLARE_CONSOLE_URL,
    pulseBaseUrl: import.meta.env.VITE_ALSET_PULSE_BASE_URL,
    pulseApiKey: import.meta.env.VITE_ALSET_PULSE_API_KEY,
    pulseSupportMessagesPath: import.meta.env.VITE_ALSET_PULSE_SUPPORT_MESSAGES_PATH,
    pusherAppId: import.meta.env.VITE_PUSHER_APP_ID,
    pusherSecrets: import.meta.env.VITE_PUSHER_SECRETS,
    pusherKey: import.meta.env.VITE_PUSHER_KEY,
    pusherCluster: import.meta.env.VITE_PUSHER_CLUSTER,
    pusherSupportChannel: import.meta.env.VITE_PUSHER_SUPPORT_CHANNEL,
}
